on: push
name: Drata/Compliance-as-Code
jobs:
    drata-iac-scan:
      runs-on: ubuntu-latest
      name: compliance-as-code-action
      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Drata Github Action
        id: drata
        uses: drata/compliance-as-code-action@v0.0.97
        env:
          DRATA_API_TOKEN: ${{ secrets.DRATA_IAC_PIPELINE_KEY }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRATA_ENVIRONMENT: 'qa'
        with:
          minimumSeverity: 'LOW'
          verboseLogging: true
